In [ ]:
#THEOROTICAL QUESTIONS START

""" 1. Purpose and Advantages of NumPy in Scientific Computing and Data Analysis
NumPy (Numerical Python) is essential for scientific computing as it provides support for large multi-dimensional arrays and matrices, alongside a collection of mathematical functions to operate on these arrays.
Advantages:
Efficiently handles large datasets with minimal memory usage.
Performs fast numerical operations such as linear algebra, statistical operations, and Fourier transforms.
Supports vectorization, allowing element-wise operations on arrays without explicit loops, enhancing both readability and performance.
Serves as the backbone for other data science libraries such as Pandas, SciPy, and TensorFlow.
Enhancing Python's Capabilities:

Python lists are not ideal for mathematical operations on large datasets due to the lack of built-in vectorization and type safety. NumPy fills this gap by providing 
ndarray, which supports fast, memory-efficient operations and data type constraints."""

In [ ]:
"""2. Comparing np.mean() and np.average()
np.mean(): This function computes the arithmetic mean (average) of the elements in an array. It calculates the 
sum of all elements and divides by the number of elements.
np.average(): Similar to np.mean() but with an additional feature—it supports weighted averages where each 
element in the array can be assigned a different weight.
When to Use:

Use np.mean() when you need a simple, unweighted average.
Use np.average() when you want to apply weights to your elements, such as in scenarios where certain elements 
have more significance in the final result."""

In [ ]:
"""3. Reversing a NumPy Array Along Different Axes
1D Array: To reverse a 1D array, you can use slicing with [::-1], which flips the array.
2D Array: For 2D arrays, you can reverse along different axes:
Along Rows: Use slicing like array[::-1, :] to reverse the rows.
Along Columns: Use array[:, ::-1] to reverse the columns.
These operations allow you to manipulate the array’s orientation, which is useful in tasks such as image processing or matrix transformations.

"""

In [ ]:
"""4. Determining the Data Type of Elements in a NumPy Array
You can determine the data type of elements in a NumPy array by accessing the dtype attribute of the array.
Importance of Data Types:
In NumPy, arrays are stored in a fixed data type (such as int32, float64, etc.), which ensures efficient memory usage.
Choosing the right data type impacts memory management and performance. For example, using int32 consumes less memory than
int64, which is important when dealing with large datasets.
Explicitly defining data types ensures that operations are fast and consistent.
"""

In [ ]:
"""5. Defining ndarrays and Their Key Features
ndarray is the fundamental array type in NumPy, representing a grid of values of the same type, indexed by a tuple of 
non-negative integers.
Key Features:

Fixed data type, ensuring all elements are of the same type.
Supports multidimensional arrays and matrices.
Performs vectorized operations (element-wise computations) without the need for loops.
Efficiently manages memory, storing data in contiguous blocks.
Differences from Python Lists:

Arrays are more memory-efficient than Python lists due to the fixed data type.
They support advanced mathematical operations directly, whereas Python lists require manual looping or library
support for similar tasks.
Arrays allow for slicing and broadcasting, which enables operations across entire arrays without needing to write
explicit loops."""

In [ ]:
"""6. Performance Benefits of NumPy Arrays over Python Lists for Large-Scale Numerical Operations
Memory Efficiency: NumPy arrays use less memory than Python lists because they store data in a contiguous block of memory, 
while lists store references to objects.
Faster Computations: Arrays are highly optimized for numerical operations and take advantage of vectorization, 
which eliminates the need for explicit loops in mathematical operations.
Built-in Functions: NumPy provides optimized functions for linear algebra, statistics, and other computations, 
significantly reducing execution time.
For large-scale operations, this leads to drastic performance improvements in both time and space complexity compared to 
standard Python lists.
"""

In [ ]:
"""7. Comparing vstack() and hstack()
vstack() (Vertical Stack): This function stacks arrays vertically (row-wise). It concatenates arrays along the first axis (axis 0).
hstack() (Horizontal Stack): This function stacks arrays horizontally (column-wise). It concatenates arrays along the second axis (axis 1).
Usage:

Use vstack() when you want to combine arrays row-wise, typically useful for adding new data points as new rows.
Use hstack() when you want to combine arrays column-wise, useful for adding new features to a dataset."""

In [ ]:
"""8. fliplr() vs flipud()
fliplr(): This function flips an array horizontally, i.e., it reverses the order of columns.
flipud(): This function flips an array vertically, i.e., it reverses the order of rows.
Effects on Array Dimensions:

fliplr() is useful for transforming images or matrices where you need to reverse columns.
flipud() is used when you want to reverse the rows, such as flipping an image upside down.
Both methods maintain the shape of the array but modify the order of elements along specific dimensions.

"""

In [ ]:
"""9. Functionality of array_split() and Handling Uneven Splits
array_split(): This function divides an array into sub-arrays along a specified axis.
Handling Uneven Splits: Unlike split(), which raises an error if the array cannot be split equally, 
array_split() allows for uneven splits, placing extra elements in the later sub-arrays.
Use Case: array_split() is particularly useful when you need to partition datasets that do not have a 
length divisible by the number of desired splits.

"""

In [ ]:
"""10. Vectorization and Broadcasting in NumPy
Vectorization: This is the process of applying operations to entire arrays instead of individual elements. It eliminates
the need for loops, resulting in more concise and faster code. For example, adding two arrays element-wise can be done in 
a single operation, like array1 + array2.
Broadcasting: Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the 
array along the larger one. This removes the need to manually reshape arrays to match dimensions before performing
element-wise operations.
Efficiency:

Vectorization and broadcasting significantly speed up numerical computations by leveraging underlying C/Fortran 
implementations, making operations faster than native Python loops.
They also make the code cleaner and more readable by removing the need for explicit iteration."""


#THEOROTICAL QUESTIONS END 

In [7]:
#PRACTICAL QUESTIONS
#1
import numpy as np
a=np.random.randint(0,100,size=(3,3))
print(a)
b=a.T #interchanging rows and columns using transpose
print(b)


[[28 71 27]
 [81  2 46]
 [12  4 35]]
[[28 81 12]
 [71  2  4]
 [27 46 35]]


In [16]:
# que2
import numpy as np
arr1=np.random.rand(10)
arr1
print("ARRAY BY RESHAPING INTO SIZE OF 2,5")
arr2=arr1.reshape(2,5)
print(arr2)

print("ARRAY AFTER RESHAPING TO 5,2")
arr3=arr2.reshape(5,2)
print(arr3)

ARRAY BY RESHAPING INTO SIZE OF 2,5
[[0.44480812 0.54207803 0.50682727 0.71594063 0.73108868]
 [0.83802732 0.14048398 0.06995614 0.90493571 0.29162234]]
ARRAY AFTER RESHAPING TO 5,2
[[0.44480812 0.54207803]
 [0.50682727 0.71594063]
 [0.73108868 0.83802732]
 [0.14048398 0.06995614]
 [0.90493571 0.29162234]]


In [20]:
# que3
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print(array_6x6)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.187462   0.91879515 0.3725224  0.10644528 0.        ]
 [0.         0.96066127 0.45687563 0.67388887 0.39399491 0.        ]
 [0.         0.56554922 0.79322921 0.756278   0.42637577 0.        ]
 [0.         0.0951421  0.49141064 0.04099975 0.49349499 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [23]:
# que4

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print(array)


[10 15 20 25 30 35 40 45 50 55 60]


In [24]:
#que5

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(arr)
lower_case = np.char.lower(arr)
title_case = np.char.title(arr)

upper_case, lower_case, title_case


(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [25]:
# que6
# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

spaced_words_array


array(['h e l l o', 'w o r l d', 'n u m p y', 'p y t h o n'], dtype='<U11')

In [26]:
# que7
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [27]:
# que8

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [28]:
# que9

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, 100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)


Random Integers:
 [159 932 150 240 502 385 388 931 575 991 187 617 385 803 897 964 461 476
 216 544  58 471 459 917 878 738 225 948 494  54 389 598 647  53 343  17
 832 522 161 673 741 511 687 822 967 562  37 736 248 297 466 332 324 594
 399 495 662 343 601 497 700 547 984 362 529 201  33 828 519 482 615 436
 766 505 178 471 323 709 415 540 443 714 842 580 792  34 576   1 738 290
 472 404 533 406 256 834 474 481 409 452]
Prime Numbers:
 [991, 617, 461, 389, 647, 53, 17, 673, 967, 37, 601, 547, 709, 443, 409]


In [33]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, 35)  # Random temperatures between 15 and 35 degrees

# Reshape the array to have 4 weeks (7 days each) and one extra week for the last 2 days
weeks = daily_temperatures.reshape(5,7)

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

print("Daily Temperatures:\n", daily_temperatures)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures:
 [22 27 18 17 27 30 29 16 15 17 22 20 34 19 15 25 26 28 34 29 20 25 22 24
 19 29 32 34 21 28 33 33 31 22 33]
Weekly Averages:
 [24.28571429 20.42857143 25.28571429 26.42857143 28.71428571]
